<?php

// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Model_User', 'doctrine');

/**
 * Model_Base_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property integer $car_id
 * @property Model_Car $Car
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
/* */
abstract class Model_Base_User extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
         ));
        
        $this->hasColumn('active', 'integer', 11);
        $this->hasColumn('group', 'integer', 3);
        
        $this->hasColumn('username', 'string', 60);
        $this->hasColumn('password', 'string', 60);
        
        $this->hasColumn('contact_name', 'string', 100);
        $this->hasColumn('email', 'string', 80);
        $this->hasColumn('phone', 'string', 30);
        
    }

    public function setUp()
    {
        
    }
};
