
<? // login/index.phtml ?>
<html>
<head>
	<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
</head>

<body>
<!-- Login Form Begin -->
<br /><br /><br />

<div align="center">
	<div id="login" align="center" style="background-color: #666666; color:#FFFFFF; font-weight: bold; padding: 0px; height: 290px; width: 360px; border: 2px ridge #000000;">
		<p style="text-align: center; font-size:20px;">
			<em><?php echo $this->siteTitle; ?></em>
			<br />(Banner Parser)
		</p>
		<p style="text-align: center; font-size:20px; text-decoration: underline;"><em>Вход</em></p>
		<? echo $this->form; ?>
		
	</div>
</div>

</body>
</html>
