
<div align="center">
	<form name="listProjects" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
	<table id="listTable" width="70%" border="1" cellspacing="0" cellpadding="5">
		<caption>Projects</caption>
		<tr>
			<th width="10%">N</th>
			<th>Title</th>
			<th colspan="3" width="20%">Action</th>
		</tr>
	<?php $i=0; foreach($this->projects as $prj): ?>
		<tr>
			<td>
				<input type="checkbox" name="active[<?php echo $prj->id; ?>]" <?php  if($prj->active): ?>checked="checked"<?php endif; ?> />
				<?php echo ++$i; ?>
			</td>
			<td><a href="<?php echo $this->baseUrl(); ?>/index/edit/project/<?php echo $prj->id; ?>"><?php echo $prj->project_title; ?></a></td>
			<td><a href="<?php echo $this->baseUrl(); ?>/index/copy/project/<?php echo $prj->id; ?>">Copy</a></td>
			<td><a href="<?php echo $this->baseUrl(); ?>/index/run/project/<?php echo $prj->id; ?>">Run</a></td>
			<td><a href="<?php echo $this->baseUrl(); ?>/index/delete/project/<?php echo $prj->id; ?>" onclick="if(confirm('Do you want to delete this Project?')) return true; else return false;">Delete</a></td>
		</tr>
	<?php endforeach; ?>
		
	</table>
	<table width="70%" style="margin: 20px 0 0 0;">
		<tr>
			<td align="right">
				<input type="submit" name="submit" value="Save" />
			</td>
		</tr>
	</table>
	
	</form>
</div>
